<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Logger\**" />
    <EmbeddedResource Remove="Logger\**" />
    <None Remove="Logger\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="PageObject\PlayrightWikiPage - Copy.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="C:\Users\ShtopiPC\.nuget\packages\allure.net.commons\2.15.0\contentFiles\any\netstandard2.0\allureConfig.Template.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright.Xunit" Version="1.59.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.core" Version="2.9.3" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
